#!/usr/bin/python3
# Use a frozen dataclass to create a class that is primarily data.
# Think of use casesof frozen and non-frozen dataclasses.
# Create a simple data class - a class whose main purpose is to hold data,
# for example:
# Point(x, y), User(id, name), Product(name, price).
# Instead of writing __init__, __repr__, and __eq__ yourself, use @dataclass.

# In case the attributes should stay immutable, use @dataclass(frozen=True).
# Good use cases: historical data, coordinates, database IDs.
# Benefits:
# * Safer to use.
# * Can often be used as dictionary keys or set members.

# Good use cases for non-frozen dataclasses.
# These represent objects whose state naturally changes:
# * Bank account balance
# * Shopping cart
# * Game character
# * Todo item (completed/not completed)
# * Download progress
# * Sensor readings that update over time
# Benefits:
# * Easy to modify fields.
# * Convenient for stateful applications.

# Rewrite the below classes as dataclasses.

class Developer():
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def __repr__(self):
        return f"Developer(name='{self.name}', age={self.age})"


class User():
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def __str__(self):
        return f"User(name='{self.name}', age={self.age})"


d = Developer("Alice", 30)
u = User("Bob", 32)

print(repr(d))  # Calls __repr__
print(u)  # Calls __str__

# Re-written as dataclasses
# __init__, __repr__, __eq__ will be autogenerated
from dataclasses import dataclass

@dataclass
class Developer():
    name: str
    age: int


@dataclass(frozen=True)
class User():
    name: str
    age: int


d = Developer("Alice", 30)
u = User("Bob", 32)

# Will print same result as above, specifically:
# Developer(name='Alice', age=30)
# User(name='Bob', age=32)
print(repr(d))  # Calls __repr__
print(u)  # Calls __str__
